// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PQ2uh4R4uzO0ppra1CAVPpDi_oEgHDU',
    appId: '1:549266111975:web:65955eb9227052c6f21142',
    messagingSenderId: '549266111975',
    projectId: 'ai-lens-7d908',
    authDomain: 'ai-lens-7d908.firebaseapp.com',
    storageBucket: 'ai-lens-7d908.appspot.com',
    measurementId: 'G-XWM11QFP6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskKsnVrPfR_h3j4mLqnL78ZmicWVZ1F4',
    appId: '1:549266111975:android:4ba47bd15a3f0f21f21142',
    messagingSenderId: '549266111975',
    projectId: 'ai-lens-7d908',
    storageBucket: 'ai-lens-7d908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCNOgAZS0xreQsuYCpXfemrQYaSEeIemI',
    appId: '1:549266111975:ios:dcff6b1776e47979f21142',
    messagingSenderId: '549266111975',
    projectId: 'ai-lens-7d908',
    storageBucket: 'ai-lens-7d908.appspot.com',
    iosClientId: '549266111975-duvlaav2rc1l2kcq7q68k7nhsfkb0lth.apps.googleusercontent.com',
    iosBundleId: 'com.example.snaptext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCNOgAZS0xreQsuYCpXfemrQYaSEeIemI',
    appId: '1:549266111975:ios:0687fd26a9cef0fff21142',
    messagingSenderId: '549266111975',
    projectId: 'ai-lens-7d908',
    storageBucket: 'ai-lens-7d908.appspot.com',
    iosClientId: '549266111975-p80s2qerj40igjme446d44hf80p1g56p.apps.googleusercontent.com',
    iosBundleId: 'com.example.snaptext.RunnerTests',
  );
}
